#语法使用"---"进行环境的分隔



spring:  profiles:    active: dev    

--- #第一个环境dev

spring:  profiles: dev  #为该环境指定一个名称    

server:  port: 8080
  servlet:    context-path: /
    
---


spring:
  profiles: /test
    
server:  port: 8090
  servlet:    context-path: /test
    
---

spring:
  profiles: prod
    
server:  port: 9000
  servlet:    context-path: /prod
    
    
    
 